"""added website link column to artist

Revision ID: 63ee77c3bd2a
Revises: e7b896f9c5f0
Create Date: 2020-10-12 23:11:12.838655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ee77c3bd2a'
down_revision = 'e7b896f9c5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
