"""deleting the seeking description column 

Revision ID: 9ab1fc29eacc
Revises: dd5bd77f5f4b
Create Date: 2020-10-14 18:21:36.962458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab1fc29eacc'
down_revision = 'dd5bd77f5f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
