"""added website link to venue

Revision ID: e7cc88922de3
Revises: 63ee77c3bd2a
Create Date: 2020-10-13 01:13:13.282126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cc88922de3'
down_revision = '63ee77c3bd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
